apiVersion: apps/v1
kind: Deployment
metadata:
  name: swe645
  labels:
    app: swe645
    test: test
spec:
  selector:
    matchLabels:
      app: swe645
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: swe645
    spec:
      containers:
      - name: swe645
        image: ganeshmandava1247889/webserver:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        # livenessProbe:
        #   httpGet:
        #     path: /status
        #     port: 5000
        #   initialDelaySeconds: 3
        #   periodSeconds: 3
       
