apiVersion: v1
kind: Service
metadata:
  name: swe645-service
  labels:
    app: swe645
spec:
  type: LoadBalancer
  selector:
    app: swe645
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 5000
